name: Bug report
description: Create a report to help us improve
title: "[Bug]: "
labels: [ "bug" ]
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: |
        Please fill out this template to the best of your ability. You can always edit this issue once you have created it.
        Read the following [**link**](https://github.com/retrospect-addon/plugin.video.retrospect/wiki/Troubleshooting) before you create a new problem report.
        Before you start make sure that you are running the latest Kodi and Retrospect version. Also check that you can watch the tv show online in a web browser.
      placeholder: |
        Provide a more detailed introduction to the issue itself, and why you consider it to be a bug
        A bug report that is not clear will be closed
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      placeholder: |
        Tell us what should happen
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual Behavior
      placeholder: |
        Tell us what happens instead
    validations:
      required: true

  - type: textarea
    id: fix
    attributes:
      label: Possible Fix
#      description: |
#        Not obligatory, but suggest a fix or reason for the bug
      placeholder: |
        Not obligatory, but suggest a fix or reason for the bug
    validations:
      required: false

  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: |
        Steps to reproduce the behavior:
        Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
    validations:
      required: false

  - type: textarea
    id: debug
    attributes:
      label: Debuglog
      description: |
        A debuglog is always mandatory when creating an issue. Provide one!
        More info can be found [**here**](https://github.com/retrospect-addon/plugin.video.retrospect/wiki/Logging)
      placeholder: |
        The debug retrospect.log can be found here
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
    #      description: |
    #      placeholder: |
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context or screenshots (if appropriate)
      description: |
        How has this bug affected you? What were you trying to accomplish?
    #      placeholder: |
    #        test me
    #      value: "A bug happened!"
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Your Environment
      multiple: true
      description: |
        Used Operating system:
        Include as many relevant details about the environment you experienced the bug in
      options:
        - Android
        - iOS
        - Linux
        - OSX
        - Raspberry-Pi
        - Windows
        - Windows UWP
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Kodi version
    validations:
      required: true

  - type: input
    attributes:
      label: Retrospect version
    validations:
      required: true
